services:
  camera:
    build: .
    container_name: camera_ir
    privileged: true
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/video0:/dev/video0       
      - /dev/media2:/dev/media2       
      - /dev/vchiq:/dev/vchiq         # Requis par libcamera
      - /dev/video0:/dev/video1    
      

    volumes:
      - ./images:/app/images
      - /run:/run
      - /run/udev:/run/udev:ro
      - /sys:/sys
    environment:
      - CAPTURE_INTERVAL=0.2
    command: python3 main.py
