services:
  camera:
    build: .
    container_name: camera_capture
    privileged: true
    devices:
      - /dev/video0:/dev/video0
      - /dev/video2:/dev/video2

    volumes:
      - ./images:/app/images
    environment:
      - CAPTURE_INTERVAL=0.2
      - MAX_CAMERAS=2
      - CAMERA_RESOLUTION=640x480
    command: python3 main.py
